server:
  port: 80

spring:
  application:
    name: cloud-consumer-feign80

eureka:
  instance:
    instance-id: cloud-consumer-feign80
    prefer-ip-address: true
  client:
    filter-only-up-instances: true
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ #,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 15000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 15000
logging:
  level:
    ml.ytooo.feignservice.Service: debug
